-- vim.g.clipboard = {
--   name = "myClipboard",
--   copy = {
--     ["+"] = "wl-copy --trim-newline",
--     ["*"] = "wl-copy --trim-newline",
--   },
--   paste = {
--     ["+"] = "wl-paste --no-newline",
--     ["*"] = "wl-paste --no-newline",
--   },
-- }

-- let g:clipboard = {
--     \   'copy': {
--     \       '+': ['wl-copy', '--trim-newline'],
--     \       '*': ['wl-copy', '--trim-newline'],
--     \   },
--     \   'paste': {
--     \       '+': ['wl-paste', '--no-newline'],
--     \       '*': ['wl-paste', '--no-newline'],
--     \   },
--     \ }
